[tool.poetry]
name = "anki-helpers"
version = "0.1.0"
description = "A CLI tool to help with Anki flashcards"
authors = ["Dzianis"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.1.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
